name: run unit tests on feature branch

on: 
  push:
    branches: 
      'feature/*'

jobs:
  run-unit-test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      - name: run unit test
        run: npm test
    
  
